const defines = {
    difficulty_settings: {
        recipe_difficulty: ["normal", "expensive"],
        technology_difficulty: ["normal", "expensive"],
    },
    direction: ["north", "south", "east", "west"],
    inventory: [
        "fuel",
        "burnt_result",
        "chest",
        "furnace_source",
        "furnace_result",
        "furnace_modules",
        "player_quickbar",
        "player_main",
        "player_guns",
        "player_ammo",
        "player_armor",
        "player_tools",
        "player_vehicle",
        "player_trash",
        "god_quickbar",
        "god_main",
        "roboport_robot",
        "roboport_material",
        "robot_cargo",
        "robot_repair",
        "assembling_machine_input",
        "assembling_machine_output",
        "assembling_machine_modules",
        "lab_input",
        "lab_modules",
        "mining_drill_modules",
        "item_main",
        "rocket_silo_rocket",
        "rocket_silo_result",
        "rocket",
        "car_trunk",
        "car_ammo",
        "cargo_wagon",
        "turret_ammo",
        "beacon_modules",
        "character_corpse",
    ],
};

export default defines;
